<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsUraPlugin>true</IsUraPlugin>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>

    <!-- URA 插件元数据 -->
    <PluginInternalName>RaceAnalyzer</PluginInternalName>
    <PluginDisplayName>保存比赛相关数据</PluginDisplayName>
    <PluginAuthor>离披</PluginAuthor>
    <PluginDescription>练习赛等</PluginDescription>
    <PluginRepositoryUrl>https://github.com/URA-Plugins/RaceAnalyzer</PluginRepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="UmamusumeResponseAnalyzer" Version="2026.9.1" />
  </ItemGroup>

</Project>
